version: '3'

networks:
  laravel:


services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: webserver
    volumes:
      - ./src/app:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
      - mysql
    networks:
      - laravel


  mysql:
    image: mysql:5.7.36
    container_name: db
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: db
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
            - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

